style = "full"
enter_accept = false
history_filter = [
    "^ ",
    "^cd",
    "^clear$",
    "^code",
    "^exit$",
    "^history",
    "^la$",
    "^ll$",
    "^ls",
    "^pwd$",
    "^reload$",
]

[sync]
records = true

[ui]
columns = ["exit", "datetime", "command"]
