#!/bin/sh
set -eu
cd "$(dirname "$0")"

if [ ! -d "/Library/Apple/usr/share/rosetta" ]; then
  echo "Please install Rosetta 2"
  exit 1
fi

if [ ! -d "/opt/homebrew" ]; then
  echo "Please install Homebrew"
  exit 1
fi

root=$PWD
target=$1

eval "$(/opt/homebrew/bin/brew shellenv)"

if [ "$target" = "homebrew" ]; then
  brew bundle --brews --casks --taps --no-lock --force --file="$root/homebrew/Brewfile"
fi

if [ "$target" = "backup" ]; then
  brew bundle dump --brews --casks --taps --no-lock --force --file="$root"/homebrew/Brewfile
  brew bundle dump --vscode --no-lock --force --file="$root"/vscode/Brewfile
fi

if [ "$target" = "zsh" ]; then
  brew install zsh
  zsh_bin=$(brew --prefix)/bin/zsh
  if ! grep -q "$zsh_bin" </etc/shells; then
    sudo sh -c "echo $zsh_bin >> /etc/shells"
    chsh -s "$zsh_bin"
  fi
  ln -s -f "$root"/zsh/zshrc "$HOME"/.zshrc
fi

if [ "$target" = "vscode" ]; then
  brew install visual-studio-code
  brew bundle --vscode --no-lock --force --file="$root/vscode/Brewfile"
  ln -s -f "$root/vscode/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
fi

if [ "$target" = "tabby" ]; then
  brew install tabby
  ln -s -f "$root/tabby/config.yaml" "$HOME/Library/Application Support/tabby/config.yaml"
fi

if [ "$target" = "sheldon" ]; then
  brew install sheldon
  mkdir -p "$HOME"/.config
  ln -s -f "$root"/sheldon/plugins.toml "$HOME"/.config/sheldon/plugins.toml
fi

if [ "$target" = "starship" ]; then
  brew install starship
  mkdir -p "$HOME"/.config
  ln -s -f "$root"/starship/starship.toml "$HOME"/.config/starship.toml
fi
