shell = "zsh"

[plugins.mise]
local = "~/.config/sheldon"

[plugins.eza]
local = "~/.config/sheldon"

[plugins.atuin]
local = "~/.config/sheldon"

[plugins.completions]
local = "~/.config/sheldon"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.F-Sy-H]
github = "z-shell/F-Sy-H"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-ssh]
github = "sunlei/zsh-ssh"
