update_check = false
style = "full"
history_filter = [
    '^cd\b',
    '^clear\b',
    '^code\b',
    '^exit\b',
    '^history\b',
    '^la\b',
    '^ll\b',
    '^logout\b',
    '^ls\b',
    '^pwd\b',
    '^reload\b',
]
command_chaining = true

[ui]
columns = ["exit", "datetime", "command"]
