style = "full"
enter_accept = false
history_filter = [
    "^cd(?:[[:space:]]|$)",
    "^code(?:[[:space:]]|$)",
    "^command[[:space:]]+-v(?:[[:space:]]|$)",
    "^git[[:space:]]+status(?:[[:space:]]|$)",
    "^history(?:[[:space:]]|$)",
    "^la$",
    "^ll$",
    "^ls(?:[[:space:]]|$)",
    "^pwd$",
    "^reload$",
]

[sync]
records = true

[ui]
columns = ["exit", "datetime", "command"]
