#!/bin/sh
set -eu
cd "$(dirname "$0")"
. "../common/prepare"

formula='visual-studio-code'
brew list $formula >/dev/null 2>&1 || brew install $formula

ln -s -f "$PWD/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
