shell = "zsh"

[plugins.xdg]
local = "~/.config/sheldon"

[plugins.homebrew]
local = "~/.config/sheldon/homebrew"

[plugins.alias]
local = "~/.config/sheldon"

[plugins.completions]
local = "~/.config/sheldon"

[plugins.history]
local = "~/.config/sheldon"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-ssh]
github = "sunlei/zsh-ssh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.prompt]
local = "~/.config/sheldon/prompt"
use = ["*.zsh"]
