# must alias
alias reload=". $HOME/.zshrc"

# disable .zsh_history
unset HISTFILE

# enable XDG
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

# terminal setup
export TERM=xterm-256color

# let's sheldon !
if command -v sheldon >/dev/null 2>&1; then
  eval "$(sheldon source)"
fi
