[ -d "/opt/homebrew" ] && eval "$(/opt/homebrew/bin/brew shellenv)"

autoload -Uz compinit
compinit

# path
[ -d "$HOME/.rd/bin" ] && export PATH="$HOME/.rd/bin:$PATH"
[ -d "$HOMEBREW_PREFIX/opt/curl" ] && export PATH="$HOMEBREW_PREFIX/opt/curl/bin:$PATH"
[ -d "$HOMEBREW_PREFIX/opt/gnu-tar" ] && export PATH="$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin:$PATH"
[ -d "$HOMEBREW_PREFIX/opt/asdf" ] && source "$HOMEBREW_PREFIX"/opt/asdf/libexec/asdf.sh
[ -d "$HOMEBREW_PREFIX/opt/sheldon" ] && eval "$(sheldon source)"

# history
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
HISTORY_IGNORE="(cd*|pwd|l[sal]*|code*|git*|relogin|history*|cat*)"
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_DUPS
setopt INC_APPEND_HISTORY

# alias
alias relogin="exec $SHELL -l"
if [ -d "$HOMEBREW_PREFIX/opt/eza" ]; then
  alias ls="eza -1"
  alias ll="eza -l --icons"
  alias la="eza -la --icons"
else
  alias ls="ls -1 --color=auto"
  alias ll="ls -l"
  alias la="ls -la"
fi

[ -d "$HOMEBREW_PREFIX/opt/starship" ] && eval "$(starship init zsh)"
