HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
HISTORY_IGNORE="(cd*|pwd|l[sal]*|code*|git*|relogin|history*|cat*)"
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_DUPS
setopt INC_APPEND_HISTORY
