# xdg
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

# disable zsh_history
unset HISTFILE

# reload alias
alias reload=". $HOME/.zshrc"

# change completion cache location
autoload -U compinit
compinit -d "$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION"
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME"/zsh/zcompcache

# enable sheldon
if command -v sheldon >/dev/null 2>&1; then
  eval "$(sheldon source)"
fi
