# xdg
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

# alias
alias reload='exec $SHELL -l'
alias ls='ls -G'
alias ll='ls -Gl'
alias la='ls -Gla'

# hist
unset HISTFILE
HISTSIZE=0
SAVEHIST=0
fc -p /dev/null 0 0

# comp
zmodload zsh/complist
autoload -Uz compinit
zstyle ':completion:*' menu select
compinit -d "$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION"

# ignition
if [[ -x ${commands[sheldon]} ]] && [[ -d "$XDG_CONFIG_HOME/sheldon" ]]; then
  eval "$(sheldon source)"
fi
