export STARSHIP_CONFIG="$HOME/.config/starship/config.toml"
export SHELDON_CONFIG_FILE="$HOME/.config/sheldon/config.toml"

[ -f "/opt/homebrew/bin/sheldon" ] && eval "$(/opt/homebrew/bin/sheldon source)"
